In [1]:
import numpy as np
import pandas as pd


In [2]:
def Ret_Pregunta06(m1, m2, m3):
    '''
    Esta función recibe tres array de Numpy de 2 dimensiones cada uno, y devuelve el valor booleano
    True si es posible realizar una multiplicación entre las tres matrices (n1 x n2 x n3),
    y el valor booleano False si no lo es
    Ej:
        n1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
        n2 = np.array([[3,3],[4,4],[5,5]])
        n3 = np.array([1,1],[2,2])
        print(Ret_Pregunta06(n1,n2,n3))
            True            -> Valor devuelto por la función en este ejemplo
        print(Ret_Pregunta06(n2,n1,n3))
            False            -> Valor devuelto por la función en este ejemplo
    '''

In [22]:
n1 = np.arange(9).reshape(3,3)
n1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
n1.shape[0] ### es el indice del shape

3

In [24]:
n1.shape[1]

3

In [9]:
n2= np.arange(6).reshape(3,2)
n2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
n3= np.arange(4).reshape(2,2)
n3

array([[0, 1],
       [2, 3]])

In [13]:
masc= np.matmul(n2,n3)
masc

array([[ 2,  3],
       [ 6, 11],
       [10, 19]])

In [28]:
n4= np.matmul(n1,n2)
n4
n4.shape

(3, 2)

In [29]:
np.matmul(n1,n4)

array([[120, 174],
       [372, 534],
       [624, 894]])

In [19]:
np.matmul(n1,n2,n3)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [ ]:
n1 = np.arange(9).reshape(3,3)
n2= np.arange(6).reshape(3,2)
n3= np.arange(4).reshape(2,2)


In [32]:
###### RTA FINAL 
def Ret_Pregunta06(m1, m2, m3):
    if n1.shape[1]==n2.shape[0]:
        if (np.dot(n1,n2).shape[1]) == n3.shape[0]:
            return True
    else:
        return False 

In [40]:
n1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
n2 = np.array([[3,3],[4,4]])
n3 = np.array([[1,1],[2,2]])

Ret_Pregunta06(n1,n2,n3)

False